# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-01 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiket',
            name='status_pembayaran',
            field=models.CharField(choices=[('0', 'Belum lunas'), ('1', 'Menunggu konfirmasi'), ('2', 'Lunas'), ('3', 'Ditolak'), ('4', 'Tidak dibayar')], max_length=1),
        ),
    ]
