# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-01 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiket', '0004_tiket_qr_code_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiket',
            name='lokasi_TO',
            field=models.CharField(choices=[('0', 'Pekanbaru'), ('1', 'Bangkinang'), ('2', 'Duri'), ('3', 'Dumai'), ('4', 'Pangkalan Kerinci')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='tiket',
            name='status_pembayaran',
            field=models.CharField(choices=[('0', 'Belum dibayar'), ('1', 'Dibayar'), ('2', 'Menunggu konfirmasi'), ('3', 'Lunas'), ('4', 'Ditolak'), ('5', 'Tidak dibayar')], default='0', max_length=1),
        ),
    ]
