# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-01 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiket', '0005_auto_20180101_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiket',
            name='bukti_pembayaran',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
