# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-07 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiket', '0008_auto_20180101_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiket',
            name='status_pembayaran',
            field=models.CharField(choices=[('0', 'Belum dibayar'), ('1', 'Dibayar'), ('2', 'Menunggu konfirmasi'), ('3', 'Lunas'), ('4', 'Ditolak'), ('5', 'Tidak dibayar'), ('6', 'Verified')], default='0', max_length=1),
        ),
    ]
