# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-15 03:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tiket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('asal_sekolah', models.CharField(max_length=40)),
                ('status_pembayaran', models.CharField(choices=[('0', 'Belum lunas'), ('1', 'Menunggu konfirmasi'), ('2', 'Lunas'), ('3', 'Ditolak')], max_length=1)),
                ('jumlah_tiket_ipa', models.IntegerField(default=0)),
                ('jumlah_tiket_ips', models.IntegerField(default=0)),
                ('lokasi_TO', models.CharField(choices=[('0', 'Pekanbaru'), ('1', 'Bangkinang'), ('2', 'Duri'), ('3', 'Dumai'), ('4', 'Pangkalan kerinci')], max_length=1)),
                ('bukti_pembayaran', models.ImageField(blank=True, height_field='height_field', null=True, upload_to='', width_field='width_field')),
                ('height_field', models.IntegerField(default=0)),
                ('width_field', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp', '-name'],
            },
        ),
    ]
