# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-15 03:27
from __future__ import unicode_literals

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiket',
            name='bukti_pembayaran',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=home.models.upload_location, width_field='width_field'),
        ),
    ]
