# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-15 04:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20171215_0327'),
    ]

    operations = [
        migrations.CreateModel(
            name='Siswa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('asal_sekolah', models.CharField(max_length=40)),
            ],
        ),
        migrations.AlterModelOptions(
            name='tiket',
            options={'ordering': ['-timestamp', '-status_pembayaran']},
        ),
        migrations.RemoveField(
            model_name='tiket',
            name='asal_sekolah',
        ),
        migrations.RemoveField(
            model_name='tiket',
            name='email',
        ),
        migrations.RemoveField(
            model_name='tiket',
            name='name',
        ),
    ]
